# https://alacritty.org/config-alacritty.html
# TOML specs can be found above

[general]

[env]

[window]

[scrolling]

[font]

[colors]

[bell]

[selection]

[cursor]

[terminal]

[terminal.shell] 
program = "/bin/fish"
args = ["-l"]

[mouse]

[hints]

[keyboard]

[debug]
